name: Publish Multiple Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/eslint-config/**'
      - 'packages/prettier-config/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ 'eslint-config', 'prettier-config' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Publish package
        run: |
          cd packages/${{ matrix.package }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
